# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GASPAR L.G.
description: "Personal website of Gaspar L.G."
baseurl: ""
url: "http://gasparlg.github.io/gasparg"
tagline: "GASPAR L.G."


# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
gems: [jekyll-paginate]
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title