# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gaspar Lobato Grinberg
description: "Gaspar Lobato Grinberg - International Sales and Marketing • Business Journalist • Wine Industry"
baseurl: "/"
url: "http://gasparlg.github.io/gasparg"
tagline: "Gaspar Lobato Grinberg"


# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
gems: [jekyll-paginate]
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title

include: [".htaccess"]  
