# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GASPAR L.G.
description: "Personal website of Gaspar L.G."
baseurl: "/"
url: "http://gasparlg.github.io/gasparg"
tagline: "GASPAR L.G."


# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
gems: [jekyll-paginate]
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
